[profile.default]
src = "contracts"
out = "artifacts"
libs = ["node_modules", "lib"]
remappings = [
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "hardhat/=node_modules/hardhat/",
]
allow_paths = ["build"]

[fmt]
line_length = 120
bracket_spacing = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config